# Generated by Django 5.1.7 on 2025-03-26 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_lawyerprofile_experience_lawyerprofile_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='city',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='lawyerprofile',
            name='city',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
