# Generated by Django 5.1.7 on 2025-03-27 00:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_consultation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consultation',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='consultation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consultations', to='users.clientprofile'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='lawyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consultations', to='users.lawyerprofile'),
        ),
    ]
